export const ACTIVE_LFG_POST_WINDOW_HOURS = 12;
export const LFG_ACTIVE_POST_LIMIT_PER_ROLE_PER_SECTION = 2;
export const LFG_CREATE_RATE_LIMIT_PER_SECTION = 4;
export const LFG_CREATE_RATE_LIMIT_WINDOW_MINUTES = 60;
