export const LFG_POST_EXPIRY_HOURS = 24;
export const LFG_ACTIVE_POST_LIMIT_PER_ROLE_PER_SECTION = 2;
export const LFG_CREATE_RATE_LIMIT_PER_SECTION = 4;
export const LFG_CREATE_RATE_LIMIT_WINDOW_MINUTES = 60;
export const STACK_MAX_GROUP_SIZE = 5;
